
--1
CREATE TABLE TRG_DEPT (
    ID NUMERIC(7, 0) PRIMARY KEY,  
    NAME VARCHAR(25) NOT NULL      
);
SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TRG_DEPT';

--2
CREATE TABLE DEPT101 (
    ID NUMERIC(7,0) PRIMARY KEY,  
    NAME VARCHAR(25) NOT NULL    
);

CREATE TABLE DEPARTMENTS (
    DEPARTMENT_ID NUMERIC(7,0) PRIMARY KEY,  
    DEPARTMENT_NAME VARCHAR(25) NOT NULL     
);

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) VALUES
(101, 'HR'),
(102, 'Finance'),
(103, 'IT'),
(104, 'Marketing'),
(105, 'Sales');

SELECT * FROM DEPT101;
 --3
 CREATE TABLE TRG_EMP (
    ID NUMERIC(7,0) PRIMARY KEY,       
    LAST_NAME VARCHAR(25) NOT NULL,    
    FIRST_NAME VARCHAR(25) NOT NULL,   
    DEPT_ID NUMERIC(7,0),              
    CONSTRAINT FK_DEPT FOREIGN KEY (DEPT_ID) REFERENCES TRG_DEPT(ID)
);

SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TRG_EMP';

--4
ALTER TABLE TRG_EMP 
ALTER COLUMN LAST_NAME VARCHAR(50) NOT NULL;

SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'TRG_EMP' AND COLUMN_NAME = 'LAST_NAME';

--5
CREATE TABLE TRG_EMPLOYEES (
    ID NUMERIC(7,0) PRIMARY KEY,      
    FIRST_NAME VARCHAR(25) NOT NULL,  
    LAST_NAME VARCHAR(50) NOT NULL,   
    SALARY DECIMAL(10,2) NOT NULL,    
    DEPT_ID NUMERIC(7,0),             
    CONSTRAINT FK_TRG_DEPT FOREIGN KEY (DEPT_ID) REFERENCES TRG_DEPT(ID) 
);
SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TRG_EMPLOYEES';

--6
DROP TABLE TRG_EMP;
SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TRG_EMP';

--7
EXEC sp_rename 'TRG_EMPLOYEES', 'TRG_EMP1';
select * from TRG_EMP1

--8
ALTER TABLE TRG_EMP1  
DROP COLUMN FIRST_NAME;

