--1.1

EXEC sp_columns MY_EMPLOYEE;

--2.2
CREATE TABLE MY_EMPLOYEE (
    ID INT NOT NULL PRIMARY KEY,
    LAST_NAME VARCHAR(25),
    FIRST_NAME VARCHAR(25),
    USERID VARCHAR(8),
    SALARY DECIMAL(9,2)
);
INSERT INTO MY_EMPLOYEE  
VALUES (1, 'Patel', 'Ralph', 'rpatel', 895);

SELECT * FROM MY_EMPLOYEE;

--3.3

INSERT INTO MY_EMPLOYEE (ID, LAST_NAME, FIRST_NAME, USERID, SALARY)  
VALUES (2, 'Dancs', 'Betty', 'bdancs', 860);

--4.4
SELECT * FROM MY_EMPLOYEE;

--5.5
DECLARE @ID INT, @LAST_NAME VARCHAR(25), @FIRST_NAME VARCHAR(25), @SALARY DECIMAL(9,2);
  
-- Assign values  
SET @ID = 3;  
SET @LAST_NAME = 'Thompson';  
SET @FIRST_NAME = 'John';  
SET @SALARY = 950;  

-- Insert data into the table  
INSERT INTO MY_EMPLOYEE (ID, LAST_NAME, FIRST_NAME, USERID, SALARY)  
VALUES (@ID, @LAST_NAME, @FIRST_NAME,  
        UPPER(LEFT(@FIRST_NAME, 1) + LEFT(@LAST_NAME, 7)),  
        @SALARY);  

-- Confirm the insertion  
SELECT * FROM MY_EMPLOYEE;

--6.6
UPDATE MY_EMPLOYEE  
SET LAST_NAME = 'Drexler'  
WHERE ID = 3;

SELECT * FROM MY_EMPLOYEE WHERE ID = 3;

--7.7
UPDATE MY_EMPLOYEE  
SET SALARY = 1000  
WHERE SALARY < 900;

SELECT * FROM MY_EMPLOYEE WHERE SALARY = 1000;


--8.8
DELETE FROM MY_EMPLOYEE  
WHERE FIRST_NAME = 'Betty' AND LAST_NAME = 'Dancs';

--9.9
DELETE FROM MY_EMPLOYEE;
select * from MY_EMPLOYEE

